mod abort;
mod agent_core;
mod agent_llm;
mod agent_loop;
mod agent_run;
mod agent_session;
mod agent_tool_process;
mod approval;
mod cache_warning;
mod checkpoint;
mod command_queue;
pub mod compact;
pub(crate) mod context;
pub mod coordinator;
mod enhanced_executor;
pub mod eval_behaviors;
pub mod eval_harness;
pub mod eval_runner;
mod hooks;
pub mod loop_engineering;
mod mcp_permission;
mod media_recovery;
mod message_factory;
mod message_lookups;
mod message_processing;
mod message_processor;
pub mod messaging;
pub mod model_catalog;
mod model_fallback;
pub(crate) mod model_list;
pub(crate) mod nudges;
mod planner;
pub(crate) mod policies;
mod prompt_builder;
mod query_loop_types;
pub mod reflection;
pub mod router;
mod session;
pub mod skills;
mod stop_hook;
mod stream_enhanced;
mod stream_stall;
mod streaming_executor;
pub mod subagent;
mod subagent_runner;
mod system_prompt_merge;
mod token_budget;
mod tool_enhanced;
mod tool_executor;
mod tool_helpers;
mod tool_result_persist;
mod tool_routing;
mod tool_use_context;
pub mod tools;
pub(crate) mod validator;
mod workflows;
pub mod worktree;

pub use agent_core::Agent;
pub use coordinator::CoordinatorMode;
pub use subagent::runner::AsyncSubagentRunner;
pub use subagent::runner::StarAgentRunner;

// Keep StarAgent public API stable for callers (main.rs uses agent::StarAgent)
pub use workflows::star_agent::StarAgent;
