/// 错误ID常量

/// 通用错误
pub const ERR_UNKNOWN: &str = "ERR_UNKNOWN";
pub const ERR_INTERNAL: &str = "ERR_INTERNAL";
pub const ERR_NOT_FOUND: &str = "ERR_NOT_FOUND";
pub const ERR_PERMISSION_DENIED: &str = "ERR_PERMISSION_DENIED";
pub const ERR_TIMEOUT: &str = "ERR_TIMEOUT";
pub const ERR_RATE_LIMITED: &str = "ERR_RATE_LIMITED";
pub const ERR_INVALID_INPUT: &str = "ERR_INVALID_INPUT";
pub const ERR_NETWORK: &str = "ERR_NETWORK";
pub const ERR_AUTH: &str = "ERR_AUTH";

/// API错误
pub const ERR_API_KEY_MISSING: &str = "ERR_API_KEY_MISSING";
pub const ERR_API_KEY_INVALID: &str = "ERR_API_KEY_INVALID";
pub const ERR_API_QUOTA_EXCEEDED: &str = "ERR_API_QUOTA_EXCEEDED";
pub const ERR_API_MODEL_NOT_FOUND: &str = "ERR_API_MODEL_NOT_FOUND";
pub const ERR_API_CONTEXT_TOO_LONG: &str = "ERR_API_CONTEXT_TOO_LONG";
pub const ERR_API_INVALID_REQUEST: &str = "ERR_API_INVALID_REQUEST";

/// 工具错误
pub const ERR_TOOL_NOT_FOUND: &str = "ERR_TOOL_NOT_FOUND";
pub const ERR_TOOL_EXECUTION_FAILED: &str = "ERR_TOOL_EXECUTION_FAILED";
pub const ERR_TOOL_TIMEOUT: &str = "ERR_TOOL_TIMEOUT";
pub const ERR_TOOL_PERMISSION_DENIED: &str = "ERR_TOOL_PERMISSION_DENIED";
pub const ERR_TOOL_INVALID_ARGS: &str = "ERR_TOOL_INVALID_ARGS";

/// 文件错误
pub const ERR_FILE_NOT_FOUND: &str = "ERR_FILE_NOT_FOUND";
pub const ERR_FILE_READ_FAILED: &str = "ERR_FILE_READ_FAILED";
pub const ERR_FILE_WRITE_FAILED: &str = "ERR_FILE_WRITE_FAILED";
pub const ERR_FILE_PERMISSION_DENIED: &str = "ERR_FILE_PERMISSION_DENIED";
pub const ERR_FILE_TOO_LARGE: &str = "ERR_FILE_TOO_LARGE";

/// 网络错误
pub const ERR_NETWORK_CONNECTION: &str = "ERR_NETWORK_CONNECTION";
pub const ERR_NETWORK_TIMEOUT: &str = "ERR_NETWORK_TIMEOUT";
pub const ERR_NETWORK_DNS: &str = "ERR_NETWORK_DNS";
pub const ERR_NETWORK_SSL: &str = "ERR_NETWORK_SSL";

/// 认证错误
pub const ERR_AUTH_TOKEN_EXPIRED: &str = "ERR_AUTH_TOKEN_EXPIRED";
pub const ERR_AUTH_TOKEN_INVALID: &str = "ERR_AUTH_TOKEN_INVALID";
pub const ERR_AUTH_SESSION_EXPIRED: &str = "ERR_AUTH_SESSION_EXPIRED";
pub const ERR_AUTH_LOGIN_FAILED: &str = "ERR_AUTH_LOGIN_FAILED";
