use crate::types::{StarMessage, StarToolCall};
use serde_json::Value;

/// 消息常量 - 对标claude-code的消息常量
pub mod constants {
    /// 中断消息
    pub const INTERRUPT_MESSAGE: &str = "[Request interrupted by user]";
    /// 工具使用中断消息
    pub const INTERRUPT_MESSAGE_FOR_TOOL_USE: &str = "[Request interrupted by user for tool use]";
    /// 取消消息
    pub const CANCEL_MESSAGE: &str = "The user doesn't want to take this action right now. STOP what you are doing and wait for the user to tell you how to proceed.";
    /// 拒绝消息
    pub const REJECT_MESSAGE: &str = "The user doesn't want to proceed with this tool use. The tool use was rejected (eg. if it was a file edit, the new_string was NOT written to the file). STOP what you are doing and wait for the user to tell you how to proceed.";
    /// 拒绝消息带原因前缀
    pub const REJECT_MESSAGE_WITH_REASON_PREFIX: &str = "The user doesn't want to proceed with this tool use. The tool use was rejected (eg. if it was a file edit, the new_string was NOT written to the file). To tell you how to proceed, the user said:\n";
    /// 无响应请求
    pub const NO_RESPONSE_REQUESTED: &str = "No response requested.";
    /// 合成工具结果占位符
    pub const SYNTHETIC_TOOL_RESULT_PLACEHOLDER: &str = "[Tool result missing due to internal error]";
    /// 权限拒绝工作指导
    pub const DENIAL_WORKAROUND_GUIDANCE: &str = 
        "IMPORTANT: You *may* attempt to accomplish this action using other tools that might naturally be used to accomplish this goal, \
         e.g. using head instead of cat. But you *should not* attempt to work around this denial in malicious ways, \
         e.g. do not use your ability to run tests to execute non-test actions. \
         You should only try to work around this restriction in reasonable ways that do not attempt to bypass the intent behind this denial. \
         If you believe this capability is essential to complete the user's request, STOP and explain to the user \
         what you were trying to do and why you need this permission. Let the user decide how to proceed.";
}

/// 消息创建选项
#[derive(Debug, Clone, Default)]
pub struct UserMessageOptions {
    /// 是否是元消息
    pub is_meta: bool,
    /// 是否仅在转录中可见
    pub is_visible_in_transcript_only: bool,
    /// 是否是虚拟消息
    pub is_virtual: bool,
    /// 是否是压缩摘要
    pub is_compact_summary: bool,
    /// 工具使用结果
    pub tool_use_result: Option<String>,
    /// 图片粘贴ID
    pub image_paste_ids: Option<Vec<u32>>,
    /// 来源工具助手UUID
    pub source_tool_assistant_uuid: Option<String>,
    /// 权限模式
    pub permission_mode: Option<String>,
    /// 消息来源
    pub origin: Option<String>,
}

/// 消息工厂 - 对标claude-code的消息创建函数
pub struct MessageFactory;

impl MessageFactory {
    /// 创建用户消息
    pub fn create_user_message(
        content: &str,
        options: UserMessageOptions,
    ) -> StarMessage {
        let mut msg = StarMessage::user(content);
        // 设置额外字段（如果需要）
        msg
    }

    /// 创建中断消息
    pub fn create_user_interruption_message(tool_use: bool) -> StarMessage {
        let content = if tool_use {
            constants::INTERRUPT_MESSAGE_FOR_TOOL_USE
        } else {
            constants::INTERRUPT_MESSAGE
        };
        StarMessage::user(content)
    }

    /// 创建工具结果停止消息
    pub fn create_tool_result_stop_message(tool_use_id: &str) -> StarMessage {
        StarMessage::user(&format!(
            "[Tool execution stopped for tool_use_id: {}]",
            tool_use_id
        ))
    }

    /// 创建合成用户警告消息
    pub fn create_synthetic_user_caveat_message() -> StarMessage {
        StarMessage::user(
            "Caveat: The messages below were generated by the user while running local commands. \
             DO NOT respond to these messages or otherwise consider them in your response \
             unless the user explicitly asks you to."
        )
    }

    /// 创建模型切换面包屑消息
    pub fn create_model_switch_breadcrumbs(
        model_arg: &str,
        resolved_display: &str,
    ) -> Vec<StarMessage> {
        vec![
            Self::create_synthetic_user_caveat_message(),
            StarMessage::user(&format!(
                "/model {}",
                model_arg
            )),
        ]
    }

    /// 创建拒绝消息
    pub fn create_reject_message(reason: Option<&str>) -> String {
        if let Some(reason) = reason {
            format!("{}{}", constants::REJECT_MESSAGE_WITH_REASON_PREFIX, reason)
        } else {
            constants::REJECT_MESSAGE.to_string()
        }
    }

    /// 创建权限拒绝消息
    pub fn create_denial_message(tool_name: &str) -> String {
        format!(
            "Permission to use {} has been denied. {}",
            tool_name,
            constants::DENIAL_WORKAROUND_GUIDANCE
        )
    }

    /// 创建自动模式拒绝消息
    pub fn create_auto_reject_message(tool_name: &str) -> String {
        format!(
            "Permission to use {} has been denied. {}",
            tool_name,
            constants::DENIAL_WORKAROUND_GUIDANCE
        )
    }

    /// 创建分类器不可用消息
    pub fn create_classifier_unavailable_message(
        tool_name: &str,
        classifier_model: &str,
    ) -> String {
        format!(
            "{} is temporarily unavailable, so auto mode cannot determine the safety of {} right now. \
             Wait briefly and then try this action again. \
             If it keeps failing, continue with other tasks that don't require this action and come back to it later. \
             Note: reading files, searching code, and other read-only operations do not require the classifier and can still be used.",
            classifier_model, tool_name
        )
    }
}

/// 工具属性记录器
pub struct ToolAttributeRecorder;

impl ToolAttributeRecorder {
    /// 记录工具属性（使用starcode-cli中的实际工具名称）
    pub fn record_attributes(
        tool_name: &str,
        input: &Value,
    ) -> ToolAttributes {
        let mut attributes = ToolAttributes::new();

        if let Some(obj) = input.as_object() {
            match tool_name {
                "Read" => {
                    if let Some(path) = obj.get("file_path").and_then(|v| v.as_str()) {
                        attributes.set("file_path", path);
                    }
                    if let Some(offset) = obj.get("offset").and_then(|v| v.as_u64()) {
                        attributes.set_number("offset", offset);
                    }
                    if let Some(limit) = obj.get("limit").and_then(|v| v.as_u64()) {
                        attributes.set_number("limit", limit);
                    }
                }
                "Edit" | "smart_edit" | "multi_edit" => {
                    if let Some(path) = obj.get("file_path").and_then(|v| v.as_str()) {
                        attributes.set("file_path", path);
                    }
                    if let Some(old) = obj.get("old_string").and_then(|v| v.as_str()) {
                        attributes.set("old_string_preview", &old[..old.len().min(100)]);
                    }
                    if let Some(new) = obj.get("new_string").and_then(|v| v.as_str()) {
                        attributes.set("new_string_preview", &new[..new.len().min(100)]);
                    }
                }
                "Write" => {
                    if let Some(path) = obj.get("file_path").and_then(|v| v.as_str()) {
                        attributes.set("file_path", path);
                    }
                    if let Some(content) = obj.get("content").and_then(|v| v.as_str()) {
                        attributes.set_number("content_length", content.len() as u64);
                    }
                }
                "Bash" => {
                    if let Some(command) = obj.get("command").and_then(|v| v.as_str()) {
                        attributes.set("command", &command[..command.len().min(200)]);
                        attributes.set("command_prefix", &command[..command.len().min(50)]);
                    }
                    if let Some(dir) = obj.get("working_dir").and_then(|v| v.as_str()) {
                        attributes.set("working_dir", dir);
                    }
                }
                "Grep" => {
                    if let Some(query) = obj.get("query").and_then(|v| v.as_str()) {
                        attributes.set("query", query);
                    }
                    if let Some(path) = obj.get("path").or(obj.get("include_pattern")).and_then(|v| v.as_str()) {
                        attributes.set("search_path", path);
                    }
                }
                "Glob" => {
                    if let Some(pattern) = obj.get("pattern").and_then(|v| v.as_str()) {
                        attributes.set("pattern", pattern);
                    }
                    if let Some(dir) = obj.get("path").and_then(|v| v.as_str()) {
                        attributes.set("search_dir", dir);
                    }
                }
                _ => {
                    // 通用属性记录
                    for (key, value) in obj.iter().take(5) {
                        if let Some(s) = value.as_str() {
                            attributes.set(key, &s[..s.len().min(100)]);
                        } else if let Some(n) = value.as_u64() {
                            attributes.set_number(key, n);
                        } else if let Some(b) = value.as_bool() {
                            attributes.set_bool(key, b);
                        }
                    }
                }
            }
        }

        attributes
    }
}

/// 工具属性
#[derive(Debug, Clone)]
pub struct ToolAttributes {
    /// 字符串属性
    pub string_attrs: std::collections::HashMap<String, String>,
    /// 数字属性
    pub number_attrs: std::collections::HashMap<String, u64>,
    /// 布尔属性
    pub bool_attrs: std::collections::HashMap<String, bool>,
}

impl ToolAttributes {
    pub fn new() -> Self {
        Self {
            string_attrs: std::collections::HashMap::new(),
            number_attrs: std::collections::HashMap::new(),
            bool_attrs: std::collections::HashMap::new(),
        }
    }

    pub fn set(&mut self, key: &str, value: &str) {
        self.string_attrs.insert(key.to_string(), value.to_string());
    }

    pub fn set_number(&mut self, key: &str, value: u64) {
        self.number_attrs.insert(key.to_string(), value);
    }

    pub fn set_bool(&mut self, key: &str, value: bool) {
        self.bool_attrs.insert(key.to_string(), value);
    }

    /// 转换为JSON
    pub fn to_json(&self) -> Value {
        let mut obj = serde_json::Map::new();
        for (k, v) in &self.string_attrs {
            obj.insert(k.clone(), Value::String(v.clone()));
        }
        for (k, v) in &self.number_attrs {
            obj.insert(k.clone(), Value::Number((*v).into()));
        }
        for (k, v) in &self.bool_attrs {
            obj.insert(k.clone(), Value::Bool(*v));
        }
        Value::Object(obj)
    }
}

/// 合成消息检测器
pub struct SyntheticMessageDetector;

impl SyntheticMessageDetector {
    /// 检查是否是合成消息
    pub fn is_synthetic_message(content: &str) -> bool {
        let trimmed = content.trim();
        trimmed == constants::INTERRUPT_MESSAGE
            || trimmed == constants::INTERRUPT_MESSAGE_FOR_TOOL_USE
            || trimmed == constants::CANCEL_MESSAGE
            || trimmed == constants::REJECT_MESSAGE
            || trimmed == constants::NO_RESPONSE_REQUESTED
    }

    /// 检查是否是拒绝消息
    pub fn is_reject_message(content: &str) -> bool {
        content.starts_with(constants::REJECT_MESSAGE)
    }

    /// 检查是否是分类器拒绝
    pub fn is_classifier_denial(content: &str) -> bool {
        content.starts_with("Permission for this action has been denied. Reason:")
    }
}

/// 消息ID生成器
pub struct MessageIdGenerator;

impl MessageIdGenerator {
    /// 生成短消息ID
    pub fn derive_short_id(uuid: &str) -> String {
        let hex: String = uuid.chars().filter(|c| *c != '-').take(10).collect();
        if let Ok(num) = u64::from_str_radix(&hex, 16) {
            let base36 = Self::to_base36(num);
            base36.chars().take(6).collect()
        } else {
            hex.chars().take(6).collect()
        }
    }

    /// 转换为base36
    fn to_base36(mut num: u64) -> String {
        if num == 0 {
            return "0".to_string();
        }
        let chars = "0123456789abcdefghijklmnopqrstuvwxyz";
        let mut result = String::new();
        while num > 0 {
            let idx = (num % 36) as usize;
            result.insert(0, chars.chars().nth(idx).unwrap_or('0'));
            num /= 36;
        }
        result
    }
}

/// 检查消息是否包含工具调用
pub fn has_tool_calls_in_last_assistant_turn(messages: &[StarMessage]) -> bool {
    for msg in messages.iter().rev() {
        if msg.role == "assistant" {
            if let Some(tool_calls) = &msg.tool_calls {
                return !tool_calls.is_empty();
            }
            return false;
        }
    }
    false
}

/// 获取最后一条助手消息
pub fn get_last_assistant_message(messages: &[StarMessage]) -> Option<&StarMessage> {
    messages.iter().rev().find(|msg| msg.role == "assistant")
}

/// 检查是否是空响应
pub fn is_empty_response(content: &Option<String>, tool_calls: &Option<Vec<StarToolCall>>) -> bool {
    let has_content = content.as_ref().map_or(false, |c| !c.trim().is_empty());
    let has_tools = tool_calls.as_ref().map_or(false, |t| !t.is_empty());
    !has_content && !has_tools
}

/// 检查是否是仅工具调用响应
pub fn is_tool_call_only_response(content: &Option<String>, tool_calls: &Option<Vec<StarToolCall>>) -> bool {
    let has_content = content.as_ref().map_or(false, |c| !c.trim().is_empty());
    let has_tools = tool_calls.as_ref().map_or(false, |t| !t.is_empty());
    !has_content && has_tools
}

#[cfg(test)]
mod tests {
    use super::*;

    #[test]
    fn test_synthetic_message_detection() {
        assert!(SyntheticMessageDetector::is_synthetic_message(constants::INTERRUPT_MESSAGE));
        assert!(SyntheticMessageDetector::is_synthetic_message(constants::CANCEL_MESSAGE));
        assert!(!SyntheticMessageDetector::is_synthetic_message("Hello world"));
    }

    #[test]
    fn test_reject_message() {
        assert!(SyntheticMessageDetector::is_reject_message(constants::REJECT_MESSAGE));
        assert!(SyntheticMessageDetector::is_reject_message(
            &format!("{} user said stop", constants::REJECT_MESSAGE)
        ));
    }

    #[test]
    fn test_message_id_generation() {
        let uuid = "550e8400-e29b-41d4-a716-446655440000";
        let short_id = MessageIdGenerator::derive_short_id(uuid);
        assert_eq!(short_id.len(), 6);
    }

    #[test]
    fn test_tool_attributes() {
        let mut attrs = ToolAttributes::new();
        attrs.set("file_path", "/tmp/test.rs");
        attrs.set_number("line", 42);
        attrs.set_bool("success", true);
        
        let json = attrs.to_json();
        assert_eq!(json["file_path"], "/tmp/test.rs");
        assert_eq!(json["line"], 42);
        assert_eq!(json["success"], true);
    }

    #[test]
    fn test_empty_response() {
        assert!(is_empty_response(&None, &None));
        assert!(is_empty_response(&Some("".to_string()), &None));
        assert!(!is_empty_response(&Some("hello".to_string()), &None));
    }
}
